# Generated by Django 6.0.2 on 2026-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_producttag_producttaglink_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Файл'),
        ),
    ]
