# Generated by Django 6.0.2 on 2026-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
