# Generated by Django 6.0.2 on 2026-04-02 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttaglink',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
