# Generated by Django 6.0.2 on 2026-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_producttaglink_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на товар'),
        ),
    ]
